# Settings
GUI_THEME = 'NeutralBlue'

# Command Running
CAN_RUN_MAIN_COMMANDS = True
CAN_RUN_SELL_COMMANDS = False
CAN_RUN_BUY_COMMANDS = False

# Shop Menu
CURRENT_SELL_COMMAND = 'none'
SELL_ITEM = False
AMOUNT_TO_SELL = 0
CURRENT_BUY_COMMAND = 'none'
BUY_ITEM = False
AMOUNT_TO_BUY = 0

# Item API
LOADED_RESOURCE_AMOUNT = 0

# Game
PREVIOUS_COMMAND = '/help'

# Debug
GAME_VERSION = 'Pre-Alpha v0.2'
DEBUG_MODE = False