# Settings
GUI_THEME = 'NeutralBlue'

# Command Running
CAN_RUN_MAIN_COMMANDS = True
CAN_RUN_SELL_COMMANDS = False
CAN_RUN_BUY_COMMANDS = False

# Shop Menu
CURRENT_SELL_COMMAND = 'none'
SELL_ITEM = False
AMOUNT_TO_SELL = 0

# Item API
LOADED_RESOURCE_AMOUNT = 0

# Game
PREVIOUS_COMMAND = '/help'

# Debug
GAME_VERSION = 'Pre-Alpha v0.3'
DEBUG_MODE = True
DEBUG_CONTAINS = False
DEBUG_INCREASE = 0