[tool.poetry]
name = "jagac-1"
version = "0.0.3"
description = ""
authors = ["MASTRIO"]

[tool.poetry.dependencies]
python = "^3.8"
cx-freeze = "^6.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
