# Settings
GUI_THEME = 'NeutralBlue'

# Shop
SHOP_COMMAND_STARTING = False
CURRENT_SHOP_COMMAND = 'e'
AMOUNT_TO_SELL = 0
LOWERED_DISPLAY_NAME = 'e'

# Item API
LOADED_RESOURCE_AMOUNT = 0

# Game
PREVIOUS_COMMAND = '/help'

# Debug
GAME_VERSION = 'Pre-Alpha v0.3'
DEBUG_MODE = False
DEBUG_CONTAINS = False
DEBUG_INCREASE = 0